kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-backend-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      name: backend
      labels:
        app: sample
        role: backend
        env: canary
    spec:
      containers:
      - name: backend
        image: gcr.io/in-gcp-ssicloudcoe/sample-img:v1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        env:
        - name: COMPONENT
          value: backend
        - name: VERSION
          value: canary
        ports:
        - name: backend
          containerPort: 8080
